on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: fabmedicalzontzon.azurecr.io
        username: ${{ secrets.acr_fabmedicalzontzon_username }}
        password: ${{ secrets.acr_fabmedicalzontzon_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/content-api" -f  "content-api/Dockerfile" -t fabmedicalzontzon.azurecr.io/fabmedicalzon:${{ github.sha }} --label dockerfile-path=content-api/Dockerfile
        docker push fabmedicalzontzon.azurecr.io/fabmedicalzon:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_fabmedicalzon_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep fabmedical-zona7fa | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace fabmedical-zona7fa`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: fabmedical-zona7fa
        container-registry-url: fabmedicalzontzon.azurecr.io
        container-registry-username: ${{ secrets.acr_fabmedicalzontzon_username }}
        container-registry-password: ${{ secrets.acr_fabmedicalzontzon_password }}
        secret-name: fabmedicalzodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: fabmedical-zona7fa
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          fabmedicalzontzon.azurecr.io/fabmedicalzon:${{ github.sha }}
        imagepullsecrets: |
          fabmedicalzodockerauth
